name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello there!'

  tests:
    needs: greeting
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout and clone repository
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          PGHOST: localhost
          PGDATABASE: test_db
          PGUSER: test_user
          PGPASSWORD: password

        run: npm t

